id: I7DBDDDAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:36:33+00:00'
last_modified: '2022-06-08T02:32:05.766707+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W14076
  title: མངོན་རྟོགས་རྒྱན་གྱི་བཤད་སྦྱར་ཡིད་ཀྱི་མུན་སེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ABE7:
      image_group_id: I1KG8771
      title: ''
      total_pages: 614
      order: 1
      base_file: ABE7.txt
    '7666':
      image_group_id: I1KG8772
      title: ''
      total_pages: 594
      order: 2
      base_file: 7666.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
